#Please keep this configuration file
server:
  port: 18082

spring:
  application:
    name: ${e3plus_service_prefix:e-erp-}order
  profiles:
      active: ${spring.profiles.active}
  main:
    allow-bean-definition-overriding: true

health.config.enabled: false

